name: instrumented tests

on: [ push ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.15.0
        with:
          api-level: 29
          target: google_apis
          profile: 4in WVGA (Nexus S)
          script: ./gradlew connectedCheck --stacktrace
